name: Tests

on:
  pull_request:
  push:

jobs:
  test:
    name: Test
    runs-on: gradle-latest
    steps:
      - name: test
        run: cd briscola-online
          gradle classes testClasses
          gradle test

