name: CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gradle

    - name: Build
      working-directory: ./briscola-online
      run: gradle classes testClasses

    - name: Test
      working-directory: ./briscola-online
      run: gradle test